import "./classify.test";
import "./normalize.test";
import "./sync.test";
import "./query-demo.test";
import "./api.test";
import "./protocol.test";
import "./exclusiveTask.test";
import "./getProblems.test";
import "./getProblemStats.test";
import "./getRandomProblem.test";
import "./getRandomProblemByFilter.test";
import "./statusSelect.test";
import "./randomProblemDisplay.test";
import "./tagsInput.test";
import "./tagMenu.test";
import "./getRatingDistribution.test";
import "./getSuccessRate.test";
import "./formatRelativeTime.test";
import { run } from "./testKit";

await run();
